apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content
  namespace: default
data:
  index.html: |
    <html>
      <head>
        <title>FluxCD App</title>
        <style>
          body {
            margin: 0;
            height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            background: #f2f2f2;
            font-family: Arial, sans-serif;
          }
          .container {
            text-align: center;
            padding: 40px;
            background: white;
            border-radius: 12px;
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
          }
          h1 {
            color: #2c3e50;
            margin-bottom: 20px;
          }
          p {
            font-size: 18px;
            color: #555;
          }
        </style>
      </head>
      <body>
        <div class="container">
          <h1>Welcome to FluxCD!</h1>
          <p>Your GitOps-powered deployment is up and running.</p>
          <p>This sample app was deployed automatically using FluxCD.</p>
        </div>
      </body>
    </html>

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: nginx:latest
        command: ["/bin/sh"]
        args:
          - -c
          - |
            rm -f /usr/share/nginx/html/index.html && \
            cp /web-content/index.html /usr/share/nginx/html/index.html && \
            nginx -g "daemon off;"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-content
          mountPath: /web-content
      volumes:
      - name: web-content
        configMap:
          name: web-content

---

apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
